### ISSUE TITLE
Production build error "Failed to set the 'src' property on HTMLScriptElement

### ISSUE THREAD

**Issue by oliverilm** [MomenSherif/react-oauth#18]
Working in development env, everything works great, but as soon as i make a release and the code gets hosted, the application crashes on initial load (only white screen is displayed)

Error displayed: `react-dom.production.min.js:216 TypeError: Failed to set the 'src' property on 'HTMLScriptElement': This document requires 'TrustedScriptURL' assignment.`

![image](https://user-images.githubusercontent.com/11034154/169991508-b4eae35d-ab38-4509-afd6-559dcb0f2a41.png)

if i open the traceback, the issue is highlighted 
![image](https://user-images.githubusercontent.com/11034154/169991686-05b5d0b7-6c02-4a6d-9118-462b7b3fcd68.png)

**Comment by MomenSherif** [comment]
@oliverilm I'm sorry for that but the issue is related to CSP is blocking any external scripts (for example here google)

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src

https://www.loginradius.com/blog/engineering/content-security-policy/

try to update CSP header on your server to allow for your scripts & google.

you can also try to load google's script alone https://developers.google.com/identity/gsi/web/guides/client-library, It should be blocked also
