### ISSUE TITLE
googleLogout function

### ISSUE THREAD

**Issue by aetrnm** [MomenSherif/react-oauth#4]
How exactly is this function supposed to work?
In source code I see only:
`declare function googleLogout(): void;`

**Comment by MomenSherif** [comment]
The new google SDK does not maintain your web app's signed-in status or session state.
The signed-in status of a Google Account, and your app's session state and signed-in status are distinct, separate concepts.
[From google docs](https://developers.google.com/identity/gsi/web/guides/migration#session_state_and_listeners)

So to log out users from your app, you don't need to call anything from the google side, log them out by updating your state,

**the only time** you need to call it is if you are using automatic `auto_select prop (true)` sign-in in google with one tap. [google docs](https://developers.google.com/identity/gsi/web/guides/automatic-sign-in-sign-out).

When users sign out of your website, they can be directed to a page where a Google One Tap prompt is automatically displayed. For this setup, auto-selection must be prohibited. Otherwise, the user is automatically signed in again, which leads to a dead-loop UX.

[implementation](https://github.com/MomenSherif/react-oauth/blob/master/src/googleLogout.ts)
```jsx
export default function googleLogout() {
  window.google?.accounts.id.disableAutoSelect();
}
```
