### ISSUE TITLE
Default GoogleLogin button does not change after login

### ISSUE THREAD

**Issue by justinhrobbins** [MomenSherif/react-oauth#9]
First off I just want to say thanks for your efforts on this project.  It's appreciated. I am trying to replace react-google-login in my React app with your react-oauth due to challenges around refresh tokens and the use of the deprecated Google API.

I am following the instructions on the ReadMe for using GoogleLogin. I think it's mostly working because:
- I see the Google button with "Sign in as xxx"
- I am able to click the button and get the popup to choose my Google account to login with.
- After selecting my Google account, the popup closes and I see the credentialResponse logged to the console.

Therefore, I think it's working correctly.  However, after that the Google button still shows "Sign in as xxx" . **Is that the expected behavior? Or am I missing something in my understanding?**

If you don't mind, can I use this Issue for an additional question? As mentioned, I am trying to avoid dealing with refresh tokens. As the Google docs state "User sign-in no longer requires you to understand or work with OAuth2 authorization codes, access tokens, or refresh tokens." I need to send a JWT to my Resource Server (not Google) which will validate the JWT with Google. If I understand correctly, I can get the JWT token from the returned credential and send that to my Resource Server.  However, the JWT still expires in 1 hour right? I'm not understanding how this new API solves my problem with having to refresh the token. What am I missing?

Thanks again for your efforts and your patience! Cheers!

**Comment by justinhrobbins** [comment]
On further thought, I assume it's my responsibility to conditionally show or not show the Google login button depending on whether the user has authenticated or not. Is that right?

**Comment by MomenSherif** [comment]
Hello @justinhrobbins, I'm happy that you give my package a try 🎉,

## First question
The new google SDK does not maintain your web app's signed-in status or session state.
The signed-in status of a Google Account, and your app's session state and signed-in status are distinct, separate concepts.
[From google docs](https://developers.google.com/identity/gsi/web/guides/migration#session_state_and_listeners)

it's now our responsibility to choose how we will persist user in our apps, You are right 👏🏻

## Second Question
you can keep you user logged-in in you application even token expiration after 1 hour, the only thing you will miss. if you are calling google APIs (ex: getting google docs for a user) you will not be authorized and will need to log-in again.

if your aim to talk to google APIs, you can use useGoogleLogin with authorization code flow, to exchange code for access & refresh token.

or like you are doing now, you can send JWT for your server and ignore exp (expires at) and create your own one in your serve,
like you are using google sign in for user info (email, name, pic) send them to the backend and use normal login flow with your backend he generates token for you with custom expiration time and you can use that.

I Don't know that you were talking about or not, but please correct me if I'm missing any thing

**Comment by MomenSherif** [comment]
`The Resource Server requires a valid JWT token to access its secured REST resources. It validates the JWT token with Google and also rejects the token if it is expired. Therefore, the expiration of the JWT token is a problem for me.`

I think you can ignore expiration because you will validate JWT with google once the user logged in then your backend will generate your JWT with your custom exp and resend it to your client, and your app will choose how to persist your user local storage, cookies ... etc

so if the user refreshes the website or come later, he will not see google login because you persisted his state and you have your backend valid JWT. I think you need to talk to Goole only when your users log in.

---

The problem with refreshing token on the client is that you need to talk to google with your client & secret id (As I Know), and I think sharing your secret id in public is not a good idea.
If you saw their network request and their refresh it using client id only, great you can implement it the same way .. and tell me how did you do that to add in the docs next week.

---

Unfortunately `personalized button` is not available in google authorization flows (token/code) 
https://developers.google.com/identity/oauth2/web/guides/overview

But I think all you need to do, and that what we used in my company to use personalized button and google login only to collect user info such as email, name, and pic

1. login in react
2. send credential (google JWT) to the backend
3. backend validate JWT with google and take from it the required data they need (ex: email to create a new user if not existing in DB)
4. backend generates a new JWT (not related to google) with custom exp time (ex: 1d) and sends it back to the client
5. from here you can store it on the client however you like to persist user
6. user refresh or any thing he is still logged in because he has token from our backend and don't need to talk to google again to obtain new one until ours expires

and tell me if I missed something I'm sorry 😅

**Comment by justinhrobbins** [comment]
I think I mostly understand your recommendation. One question: If we only interact with google login to collect the user info then how can the user revoke their access via Google? For example on Google's [Apps with access to your account](https://myaccount.google.com/permissions?continue=https%3A%2F%2Fmyaccount.google.com%2Fsecurity) page? Is it still possible?

**Comment by MomenSherif** [comment]
## Revoking a token
- from google's page it will revoke their google APIs access and will need to consent again when they come back, If they revoked from here, I don't know how you will be notified from google


- And if you need to remove their data from DB
   - revoking from you app can be done in two steps, call this method from google to revoke their consent https://developers.google.com/identity/gsi/web/guides/revoke (maybe I will export a small function in v0.2.2 for that)
   - Delete your user's data from your backend
  
  
  ---
  ## Refresh token
  
  It's not a problem to refresh the token on the client or on the server, the small problem is how we can obtain a refresh token from google
  
  the only way is using Authorization code flow [Google's Docs](https://developers.google.com/identity/oauth2/web/guides/choose-authorization-model)
  - Your client login to google and obtain a `code` (authorization code)
  - Send it to backend to exchange this code with
        - `access_token` (to talk with google APIs)
        - `refresh_token` (to refresh user's token)
        - `id_token` (JWT contains all user's info)
 - Backend responded back to the client with the tokens
 
**Client**
```jsx
const googleLogin = useGoogleLogin({
  onSuccess: async ({ code }) => {
    const tokens = await axios.post('http://localhost:3001/auth/google', {  // http://localhost:3001/auth/google backend that will exchange the code
      code,
    });

    console.log(tokens);
  },
  flow: 'auth-code',
});
```

In backend, you can do this by sending requests to google or using their libraries
[google-auth-library-java](https://github.com/googleapis/google-auth-library-java)

I'm sorry I don't know Java, But I will give you an example with nodejs

**Backend using express**
```js
require('dotenv').config();
const express = require('express');
const {
  OAuth2Client,
} = require('google-auth-library');
const cors = require('cors');

const app = express();

app.use(cors());
app.use(express.json());

const oAuth2Client = new OAuth2Client(
  process.env.CLIENT_ID,
  process.env.CLIENT_SECRET,
  'postmessage',
);


app.post('/auth/google', async (req, res) => {
  const { tokens } = await oAuth2Client.getToken(req.body.code); // exchange code for tokens
  console.log(tokens);
  
  res.json(tokens);
  
  // without google-auth-library

  // const body = new URLSearchParams({
  //   code: '4/0AX4XfWgTgaGdYRY28LMT8Xlu3t1QBzUejcyOy0wHq8zaFjZoLffopQTgranqRPJnxBQ5mg',
  //   client_id: clientId,
  //   client_secret: clientSecret,
  //   grant_type: 'authorization_code',
  //   redirect_uri: 'postmessage',
  // });

  // const { data } = await axios.post(
  //   'https://oauth2.googleapis.com/token',
  //   body,
  //   { headers: { 'Content-Type': 'application/x-www-form-urlencoded' } },
  // );
  // res.json(data);
});

app.post('/auth/google/refresh-token', async (req, res) => {
  const user = new UserRefreshClient(
    clientId,
    clientSecret,
    req.body.refreshToken,
  );
  const { credentials } = await user.refreshAccessToken(); // optain new tokens
  res.json(credentials);

  // without google-auth-library

  // const body = new URLSearchParams({
  //   client_id: clientId,
  //   client_secret: clientSecret,
  //   grant_type: 'refresh_token',
  //   refresh_token: req.body.refreshToken,
  //   redirect_uri: 'postmessage',
  // });

  // const { data } = await axios.post(
  //   'https://oauth2.googleapis.com/token',
  //   body,
  //   {
  //     headers: {
  //       'Content-Type': 'application/x-www-form-urlencoded',
  //     },
  //   },
  // );
  // console.log(data)
})

app.listen(3001, () => console.log(`server is running`));
``

**Comment by justinhrobbins** [comment]
@MomenSherif you've been very helpful and provided a lot of useful guidance. I will try to convert to using Authorization code flow. I think we can close this Issue. Thanks again!
